sudo: required
services:
    - docker

before_install:
    - docker build -t dsullivansr/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true dsullivansr/react-test npm run test

after_success:
    # Build multi container docker images.
    - docker build -t dsullivansr/multi-client ./client
    - docker build -t dsullivansr/multi-nginx ./nginx
    - docker build -t dsullivansr/multi-server ./server
    - docker build -t dsullivansr/multi-worker ./worker

    # Log into docker hub.
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    # Push docker images to docker hub.
    - docker push dsullivansr/multi-client
    - docker push dsullivansr/multi-nginx
    - docker push dsullivansr/multi-server
    - docker push dsullivansr/multi-worker

# AWS Deploy
deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env-1
    bucket_name: elasticbeanstalk-us-east-1-530298841741
    bucker_path: docker-multi
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    edge: true
    on:
        branch: master